# Generated by Django 5.1.1 on 2024-09-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_collection_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='collections', to='store.product'),
        ),
    ]
