# Generated by Django 5.1.1 on 2024-09-19 23:39

import django.db.models.deletion
from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_collection_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.collection'),
        ),
    ]
